[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_THEME = "minimal-bootstrap-hugo-theme"
  HUGO_BASEURL = "https://minimal-bootstrap-hugo-theme.netlify.com/"